# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(210, 50, 160, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Variant1Button = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.Variant1Button.setObjectName("Variant1Button")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.Variant1Button)
        self.verticalLayout.addWidget(self.Variant1Button)
        self.Variant2Button = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.Variant2Button.setObjectName("Variant2Button")
        self.buttonGroup.addButton(self.Variant2Button)
        self.verticalLayout.addWidget(self.Variant2Button)
        self.Variant3Button = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.Variant3Button.setObjectName("Variant3Button")
        self.buttonGroup.addButton(self.Variant3Button)
        self.verticalLayout.addWidget(self.Variant3Button)
        self.Variant4Button = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.Variant4Button.setObjectName("Variant4Button")
        self.buttonGroup.addButton(self.Variant4Button)
        self.verticalLayout.addWidget(self.Variant4Button)
        self.WordLabel = QtWidgets.QLabel(Form)
        self.WordLabel.setGeometry(QtCore.QRect(50, 130, 111, 21))
        self.WordLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.WordLabel.setObjectName("WordLabel")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 260, 401, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BackButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.BackButton.setObjectName("BackButton")
        self.horizontalLayout.addWidget(self.BackButton)
        self.CounterLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.CounterLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.CounterLabel.setObjectName("CounterLabel")
        self.horizontalLayout.addWidget(self.CounterLabel)
        self.ForwardButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ForwardButton.setObjectName("ForwardButton")
        self.horizontalLayout.addWidget(self.ForwardButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Variant1Button.setText(_translate("Form", "Вариант1"))
        self.Variant2Button.setText(_translate("Form", "Вариант 2"))
        self.Variant3Button.setText(_translate("Form", "Вариант 3"))
        self.Variant4Button.setText(_translate("Form", "Вариант 4"))
        self.WordLabel.setText(_translate("Form", "Слово"))
        self.BackButton.setText(_translate("Form", "<-"))
        self.CounterLabel.setText(_translate("Form", "Число вопросов"))
        self.ForwardButton.setText(_translate("Form", "->"))
